### PR TITLE
add warning about forking of decentralized ledger system

### PR DESCRIPTION
**Pull request by kdenhartog**
Signed-off-by: Kyle Den Hartog <kyle.denhartog@mattr.global>

Addresses issue #590

### CODE REVIEW

**Comment by OR13** [comment]
@kdenhartog make sure to never commit the html, only the markdown files...

**Comment by csuwildcat** [comment]
Kyle, if you just put this in the same place in the MD file, it will render the warning:

```markdown
:::warning Ledger Forking
Implementers should be aware that if the underlying decentralized ledger system were to fork, the identifiers will also be forked. In this case, the a new identifier must be created either through an indication at the network layer or with a completely new method name to identify the decentralized identifiers of the forked network.
:::
```

**Comment by kdenhartog** [comment]
fixed, thanks for the help.

**Comment by OR13** [comment]
@kdenhartog we changed the structure on you, sorry :)

**Comment by kdenhartog** [comment]
> 
> 
> @kdenhartog we changed the structure on you, sorry :)

All good, should I do anything else other than resolve the merge conflict? Now that I know spec-up is about editing markdown files I'll stick with that. I personally enjoy writing in markdown over the other formats most specs require. IETF with XML was probably the least fun, but I think I just picked the wrong tool in that case cause I've seen markdown tools for producing IETF drafts as well.

**Pull request merged**
