### PR TITLE
Update swagger API to use underscores

### PR DESCRIPTION
**Pull request by troyronda**
Updated JSON properties to use underscores.

Closes: #579

### CODE REVIEW

**Comment by troyronda** [comment]
Possible followup: what is the convention to use for query parameters?
Examples:
- `max-size`
- `transaction-time-hash`

**Comment by OR13** [comment]
@thehenrytsai @troyronda @kdenhartog I've always been confused why we use kebab-case for query params... I prefer understore (snake_case) for consistency.

**Comment by OR13** [comment]
@troyronda  I recommend you switch the params to snake_case, and wait for someone to object.

**Comment by troyronda** [comment]
@OR13 done

**Comment by kdenhartog** [comment]
@OR13 number 4 in consistency is key section here gives a reason why. https://restfulapi.net/resource-naming/

With that said, we typically use kebab-case but I'm not going to object if api endpoints use snake case.

**Comment by OR13** [comment]
@kdenhartog great reference... I was assuming that this only applied to query strings, but seems like you are thinking that the path segments should also be considered... 

Can you open an issue and cite that resource, I feel like we should base our API on a styleguide... and I would be fine noting that paths should be kebab case, query strings and json objects should be snake-case.

**Comment by kdenhartog** [comment]
> snake-case.

snake_case. FTFY 😎 

Also, will do.

**Comment by csuwildcat** [comment]
To clarify this:

1. Underscores should be used in JSON payload keys
2. Dashes should be used for path segments and URL Parameters
3. If we ever specify internal APIs in IDL, functions should be camel cased, and variables likely underscored (less rigidity on this last item)

**Comment by OR13** [comment]
^ move discussion to github issue. don't discuss things on a merged PR.

**Pull request merged**
