### PR TITLE
Remove method prefix from initial state

### PR DESCRIPTION
**Pull request by OR13**
addresses https://github.com/decentralized-identity/sidetree/issues/769

Removes the method prefix from `initial-state` did parameter.

### CODE REVIEW

**Comment by jmandel** [comment]
I missed a window to comment since it looks this was created and merged within an hour, but this is a breaking change to long-form DIDs. I thought our intention was to avoid making breaking changes to long-form DIDs at this stage. The PR here and issue at https://github.com/decentralized-identity/sidetree/issues/769 don't explain the rationale.

If I'm missing something, please let me know. (I'd prefer to see no change, or a spec that ensures `-ion-initial-state` remains acceptable even if `initial-state` is preferred.)

**Comment by csuwildcat** [comment]
@jmandel we can make this a backwards compatible change in the ION implementation

**Comment by jmandel** [comment]
Thanks! Is there a spot where we document these kinds of additional rules for `ion`?

**Comment by csuwildcat** [comment]
@jmandel I will get together an ION spec that is mostly refs to Sidetree, but with the bits that are specific to it. That's one of my deliverables for July

**Pull request merged**
