### PR TITLE
Improve the performance of the ReadableStream.ts

### PR DESCRIPTION
**Pull request by sambarnes**
In response to #317 

Add an optional parameter `contentLength?: number` to `ReadableStream.readAll()` such that, when provided, the returned Buffer's content is preallocated and populated using `content.fill()` rather than `content.concat()`. Additionally, add a helper function `ReadableStream.getContentLengthFromHeader()` to perform the common action of getting the `"Content-Length"` header value from `response.headers`.

All usages that I could find have been updated to use the new function signature.

I'm still fairly new to JavaScript-land so I likely have written something non-idiomatically or weird in some other way. I'd appreciate any small pointers and would be happy to fix any strangeness.

### CODE REVIEW

**Comment by sambarnes** [comment]
@mudiali I appreciate the feedback. As I am new to the project I was hesitant to move straight to including further abstraction than was immediately necessary. I do agree with your points though, and have attempted to incorporate them in the latest changes.

**Comment by OR13** [comment]
This has a conflict and is 16 days old... consider closing.

**Comment by sambarnes** [comment]
Handled minor conflict. Let me know if there's anything else that stands out as needing fixed in order to close out original issue

**Comment by OR13** [comment]
This has conflicts and will be closed in 1 week.

**Comment by OR13** [comment]
@sambarnes @thehenrytsai I have resolved the merge conflict in this... it still needs a review to be merged or closed / rejected.

**Comment by OR13** [comment]
Closing due to inactivity

**Comment by sambarnes** [comment]
Downside of trying to take the low hanging fruit I guess :)

**Comment by OR13** [comment]
@sambarnes thanks for trying, my OCD just can't leave a PR open for this long. I suggest you open an issue and get @thehenrytsai to agree to the changes before opening another PR.

**Comment by sambarnes** [comment]
No worries! It's open at #317 already though, so maybe someone can just use this code when that issue gets attention.

**Pull request closed without merging**
