### PR TITLE
#430 parse blk.dat file

### PR DESCRIPTION
**Pull request by isaacJChen**
TL:DR what I am parsing:
image

Full detail of how blk.dat files work:
https://learnmeabitcoin.com/guide/blkdat

### CODE REVIEW

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/issues/430

**Comment by sambarnes** [comment]
Ah right on, I was gonna take a stab at this for fun but see ya started already.

I was taking a look at the parity-bitcoin code and seeing if you could just use wasm-bindgen to call the Rust functions from sidetree without major modifications. Anyways, found some notes that may or may not be helpful if you continue implementing in TS: https://github.com/paritytech/parity-bitcoin/blob/master/import/src/block.rs#L15

**Comment by isaacJChen** [comment]
@sambarnes Feel free to go through the PR if you are interested :)

**Comment by OR13** [comment]
This PR has been open for 9 days... @thehenrytsai @mudiali can you request changes / approve / merge?

**Comment by csuwildcat** [comment]
The PR will likely need some further additions before it is ready to merge, but I would rather defer to @isaacJChen on how he wants to handle the open PR, vs closing it as a procedural move.

**Comment by isaacJChen** [comment]
This PR can be merged separately from the rest. It's basically a script that can parse block files, and there will be another application running that uses this script. I think the main reason we haven't looked at it much is because we couldn't decide the direction of this issue. 

This code doesn't touch anything currently exist in sidetree so it is safe to merge regardless, but I'm also fine with leaving it out for now.

**Comment by OR13** [comment]
@isaacJChen can you add a review, approving this PR or request changes.

**Comment by isaacJChen** [comment]
I made this PR so it's up to others lol

**Comment by OR13** [comment]
@csuwildcat  @thehenrytsai @mudiali I will close this PR in 24 hours, its been open for almost a full month.

**Comment by isaacJChen** [comment]
linked in issue, will revisit when ready.

**Pull request closed without merging**
